# Generated by Django 3.2.7 on 2021-09-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_teacher_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='statut',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='statut',
            field=models.BooleanField(default=True),
        ),
    ]
